name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Log in to GHCR
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')/my-app:latest .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.actor }}/my-app:latest
